db.categorias.insertMany([

    { "cod" : "001",
      "nombreCategoria": "Vegetales",
      "paisOrigenProductos": "Irlanda",
      "vegano": true,
      "lactosa": false,
      "gluten": true,
      "ImpuestoAduanas": 0.20,
    
    },
    { "cod" : "002",
    "nombreCategoria": "Esenciales",
    "paisOrigenProductos": "Alemania",
    "vegano": true,
    "lactosa": false,
    "gluten": false,
    "ImpuestoAduanas": 0.25,
    },
    { "cod" : "003",
    "nombreCategoria": "Carnes",
    "paisOrigenProductos": "Italia",
    "vegano": false,
    "lactosa": false,
    "gluten": true,
    "ImpuestoAduanas": 0.15,
    },
    { "cod" : "004",
    "nombreCategoria": "Pescados",
    "paisOrigenProductos": "España",
    "vegano": false,
    "lactosa": true,
    "gluten": false,
    "ImpuestoAduanas": 0.35,
    },
    { "cod" : "005",
    "nombreCategoria": "Frutas",
    "paisOrigenProductos": "Marruecos",
    "vegano": false,
    "lactosa": false,
    "gluten": false,
    "ImpuestoAduanas": 0.05,
    },
    { "cod" : "006",
    "nombreCategoria": "Higiene",
    "paisOrigenProductos": "Portugal",
    "vegano": true,
    "lactosa": false,
    "gluten": false,
    "ImpuestoAduanas": 0.10,
    },
    { "cod" : "007",
    "nombreCategoria": "Conservas",
    "paisOrigenProductos": "España",
    "vegano": false,
    "lactosa": true,
    "gluten": true,
    "ImpuestoAduanas": 0.30,
    },
    { "cod" : "008",
    "nombreCategoria": "Lacteos",
    "paisOrigenProductos": "Alemania",
    "vegano": true,
    "lactosa": true,
    "gluten": true,
    "ImpuestoAduanas": 0.25,
    },
])