db.almacen.insertMany([

    { "_id" : 1,
      "producto": "macarrones",
      "precioCompra": 2,
      "precioVENT": 8,
      "fecha": new Date(2020,04,01),
      "unidades": 10,
      "Distribuidora": 1,
      "cod": "002",
    
    },{
      "_id" : 2,
      "producto": "Harina",
      "precioCompra": 1,
      "precioVENT": 3,
      "fecha": new Date(2020,05,11),
      "unidades": 22,
      "Distribuidora": 3,
      "cod": "001",
    },{
      "_id" : 3,
      "producto": "Azucar",
      "precioCompra":5,
      "precioVENT": 5.5,
      "fecha": new Date(2020,03,12),
      "unidades": 5,
      "Distribuidora": 4,
      "cod": "002",
    },{
      "_id" : 4,
      "producto": "Sal",
      "precioCompra": 1,
      "precioVENT": 3,
      "fecha": new Date(2020,08,10),
      "unidades": 20,
      "Distribuidora": 1,
      "cod": "007",
    },{
      "_id" : 5,
      "producto": "mantequilla",
      "precioCompra": 0.5,
      "precioVENT": 1,
      "fecha": new Date(2020,03,01),
      "unidades": 5,
      "Distribuidora": 2,
      "cod": "002",
    },{
      "_id" : 6,
      "producto": "Hielos",
      "precioCompra": 10,
      "precioVENT": 80,
      "fecha": new Date(2020,04,11),
      "unidades": 25,
      "Distribuidora": 3,
      "cod": "007",
    },{
      "_id" : 7,
      "producto": "Pescado frito",
      "precioCompra": 7,
      "precioVENT": 15,
      "fecha": new Date(2020,03,12),
      "unidades": 27,
      "Distribuidora": 2,
      "cod": "004",
    },{
      "_id" : 8,
      "producto": "Carne",
      "precioCompra": 1,
      "precioVENT": 2,
      "fecha": new Date(2020,05,10),
      "unidades": 2,
      "Distribuidora": 1,
      "cod": "003",
    },{
      "_id" : 9,
      "producto": "margarina",
      "precioCompra": 10,
      "precioVENT": 20,
      "fecha": new Date(2020,05,10),
      "unidades": 10,
      "Distribuidora": 3,
      "cod": "002",

    },
    {
        "_id" : 10,
        "producto": "Maizena",
        "precioCompra": 1,
        "precioVENT": 4,
        "fecha": new Date(2021,05,10),
        "unidades": 50,
        "Distribuidora": 2,
        "cod": "001",

    },
    {
        "_id" : 11,
        "producto": "Crema",
        "precioCompra": 3,
        "precioVENT": 4,
        "fecha": new Date(2021,04,11),
        "unidades": 5,
        "Distribuidora": 4,
        "cod": "006",

      },
      {
        "_id" : 12,
        "producto": "avena",
        "precioCompra": 0.10,
        "precioVENT": 0.80,
        "fecha": new Date(2019,04,11),
        "unidades": 50,
        "Distribuidora": 2,
        "cod": "001",
      } ,
      {
          "_id" : 13,
          "producto": "Champu",
          "precioCompra": 4,
          "precioVENT": 7,
          "fecha": new Date(2021,04,11),
          "unidades": 51,
          "Distribuidora": 1,
          "cod": "006",
  
        },
        {
          "_id" : 14,
          "producto": "Maiz",
          "precioCompra": 3,
          "precioVENT": 17,
          "fecha": new Date(2021,04,11),
          "unidades": 11,
          "Distribuidora": 4,
          "cod": "007",
  
        },
        {
          "_id" : 15,
          "producto": "Platano",
          "precioCompra": 1,
          "precioVENT": 3,
          "fecha": new Date(2021,04,11),
          "unidades": 11,
          "Distribuidora": 2,
          "cod": "005",
  
        },
        {
          "_id" : 16,
          "producto": "manzana",
          "precioCompra": 2,
          "precioVENT": 3,
          "fecha": new Date(2021,04,11),
          "unidades": 21,
          "Distribuidora": 2,
          "cod": "005",
  
        },
        {
          "_id" : 17,
          "producto": "Sardinas",
          "precioCompra": 10,
          "precioVENT": 15,
          "fecha": new Date(2021,04,11),
          "unidades": 162,
          "Distribuidora": 4,
          "cod": "004",
  
        },
        {
          "_id" : 18,
          "producto": "Berenjenas",
          "precioCompra": 1,
          "precioVENT": 3,
          "fecha": new Date(2021,04,11),
          "unidades": 23,
          "Distribuidora": 1,
          "cod": "001",
  
        },
        {
          "_id" : 19,
          "producto": "queso",
          "precioCompra": 10,
          "precioVENT": 30,
          "fecha": new Date(2021,04,11),
          "unidades": 12,
          "Distribuidora": 3,
          "cod": "008",
  
        },
        {
          "_id" : 20,
          "producto": "Leche",
          "precioCompra": 2,
          "precioVENT": 4,
          "fecha": new Date(2021,04,11),
          "unidades": 43,
          "Distribuidora": 4,
          "cod": "008",
  
        },
        {
          "_id" : 21,
          "producto": "Yogurth",
          "precioCompra": 4,
          "precioVENT": 5,
          "fecha": new Date(2021,04,11),
          "unidades": 63,
          "Distribuidora": 2,
          "cod": "008",
  
        }
    ])